"use client"

import { useEffect } from "react"

export default function SwRegister() {
  useEffect(() => {
    if (typeof window === "undefined") return
    if (!('serviceWorker' in navigator)) return
    // Only register in production builds
    if (process.env.NODE_ENV !== 'production') return

    // Try common SW filenames generated by different PWAs/next-pwa setups
    const tryRegister = async () => {
      try {
        await navigator.serviceWorker.register('/sw.js')
        // console.log('Service worker registered: /sw.js')
      } catch (e1) {
        try {
          await navigator.serviceWorker.register('/service-worker.js')
          // console.log('Service worker registered: /service-worker.js')
        } catch (e2) {
          // console.warn('Service worker registration failed', e1, e2)
        }
      }
    }

    tryRegister()
  }, [])

  return null
}
